#!/bin/sh

alias ls='ls --color=auto'
alias ll='ls -lah'
alias la='ls -A'

alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

fopen() {
    xdg-open "$(find $HOME -type f | fzf)"
}

viopen() {
    vim "$(find $HOME -type f | fzf)"
}
